// This module contains various constants that are
// platform specific for arm1176

enum InterruptSources {
    WatchDog = 0,
    Software = 1,
    CommsRx = 2,
    CommsTx,
    Timers01,
    Timers23,
    GPIO0,
    GPIO1,
    GPIO2,
    GPIO3,
    RTC,
    SSP,
    UART0,
    UART1,
    UART2,
    SCI0,
    CLCDC,
    DMA,
    PWRFAIL,
    MBX,
    GND,
    VICINTSOURCE21,
    VICINTSOURCE22,
    VICINTSOURCE23,
    VICINTSOURCE24,
    VICINTSOURCE25,
    VICINTSOURCE26,
    VICINTSOURCE27,
    VICINTSOURCE28,
    VICINTSOURCE29,
    VICINTSOURCE30,
    VICINTSOURCE31,
}
